### PR TITLE
ext: fix missing build.js

### PR DESCRIPTION
**Pull request by drjova**
Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by drjova** [comment]
`build.js` https://github.com/inveniosoftware/invenio-theme/pull/20

**Comment by lnielsen** [comment]
As discussed in inveniosoftware/invenio-theme#20 let's remove ``REQUIREJS_CONFIG`` from Invenio-Assets and move it to Invenio-Theme instead.

**Comment by drjova** [comment]
:+1: done

**Comment by jirikuncar** [comment]
Shall we adapt tests or keep the `invenio-assets` untouched - closing this PR?

**Pull request merged**
