### PR TITLE
docs: fix author name

### PR DESCRIPTION
**Pull request by helix84**
* Fixed my own git name in AUTHORS.rst.

* Added .kwalitee.yml with my alternative git name (present in a commit
  originated from GitHub).

Signed-off-by: Ivan Masár <helix84@centrum.sk>

### CODE REVIEW

**Comment by helix84** [comment]
kwalitee check messages still complains:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 215: ordinal not in range(128)

I fixed kwalitee, this should pass after the PR is merged: inveniosoftware/kwalitee#98

**Comment by jirikuncar** [comment]
@helix84 can you write the bullet points in present tense (see http://invenio.readthedocs.io/en/latest/technology/git.html?highlight=git%20message#r2-remarks-on-commit-log-messages)?

PS: The bullet points are not necessary for really tiny commits that fix only "typos" or "style" issues 😉 .

**Comment by jirikuncar** [comment]
```
missing from sdist:
  .kwalitee.yml
suggested MANIFEST.in rules:
  include *.yml
```

**Comment by helix84** [comment]
@jirikuncar Done.

**Comment by jirikuncar** [comment]
@helix84 can you rebase since: This branch is out-of-date with the base branch

**Comment by helix84** [comment]
@jirikuncar Ready.

**Pull request merged**
