### PR TITLE
docs: new maintainer

### PR DESCRIPTION
**Pull request by drjova**
Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by jirikuncar** [comment]
LGTM (let's wait for @lnielsen so we have over 66% agreement)

**Comment by tiborsimko** [comment]
The commit message may better be `docs: new maintainer`, since we don't have `maintainers` component :smile: although we could.

Example: https://github.com/inveniosoftware/invenio/commit/3c156df77b4896b0e69b1a7f559d03011e65e445

**Comment by jirikuncar** [comment]
LGTM (let's wait for @lnielsen so we have over 66% agreement)

**Comment by lnielsen** [comment]
LGTM

**Pull request merged**
